# Generated by Django 4.1.7 on 2023-08-20 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя пользователя')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='Город')),
                ('profession', models.CharField(blank=True, max_length=128, null=True, verbose_name='Профессия')),
                ('summary', models.CharField(blank=True, max_length=128, null=True, verbose_name='Bio')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('vk', models.CharField(default='https://vk.com', max_length=128, verbose_name='VK')),
                ('github', models.CharField(default='https://github.com', max_length=128, verbose_name='Github')),
                ('youtube', models.CharField(default='https://youtube.com', max_length=128, verbose_name='YouTube')),
                ('website', models.CharField(default='https://mysite.com', max_length=128, verbose_name='Сайт')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='users.profile', verbose_name='Подписан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Содержимое')),
                ('seen', models.BooleanField(default=False, null=True, verbose_name='Просмотрено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='users.profile', verbose_name='Получатель')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['seen', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
                'ordering': ['created'],
                'unique_together': {('name', 'slug', 'profile')},
            },
        ),
    ]
